[package]
name = "rstest"
version = "0.2.1"
authors = ["Michele d'Amico <michele.damico@gmail.com>"]
homepage = "https://github.com/la10736/rstest"
description = """
A simple `pytest` clone for Rust. It use procedural macro
to implement fixtures and table based tests.
"""
repository = "https://github.com/la10736/rstest"
license = "MIT/Apache-2.0"
keywords = ["test", "fixture"]
categories = ["development-tools::testing"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.12", features = ["full", "parsing", "extra-traits"] }
proc-macro2 = { version = "0.2" }
quote = "0.4"

[dev-dependencies]
temp_testdir = "0.2"
