[package]
name = "playground"
version = "0.1.0"
authors = ["michele <michele.damico@gmail.com>"]
edition = "2018"
exclude = [
    "playground",
    "rstest_fixtures",
]


[features]
default = []
# Depends on nightly
trace_all = []

[dependencies]
lazy_static = "*"

[dependencies.rstest]
path = "../"
version = "*"
