[package]
name = "playground"
version = "0.1.0"
authors = ["michele <michele.damico@gmail.com>"]
edition = "2018"


[features]
default = []
# Depends on nightly
trace_all = []


[dependencies.rstest]
path = "../"
version = "*"
